### PR TITLE
Add the support for real-time logging

### PR DESCRIPTION
**Pull request by yesw2000**
Hi Paul,

I added the necessary code to support the **real-time logging**. The code has already been tested on panda jobs. I added the realtime logging job in the threads of payload.py. The core script is **pilot/util/realtimelogger.py**. Please adjust it to fit into your design of fast_monitor_tasks.

Best,

Shuwei

### CODE REVIEW

**Comment by PalNilsson** [comment]
Hi Shuwei,
Can you please make this PR to https://github.com/PalNilsson/pilot3/tree/next instead? I will look at it asap. I have halted Pilot 2 development now and will only make further Pilot 2 releases for urgencies until Pilot 3 can be used instead (~1+ weeks). 
Cheers, Paul

**Comment by yesw2000** [comment]
Hi Paul,

Sure. I will change the upstream to PalNilsson/pilot3, merge it first locally. Then I will make a new pull request.

Best,

--Shuwei

**Comment by yesw2000** [comment]
Hi Paul,

I made a new PR under pilot3/tree/next:

https://github.com/PalNilsson/pilot3/pull/4

Best,

--Shuwei

**Comment by PalNilsson** [comment]
Implemented in Pilot 3

**Pull request closed without merging**
